# Generated by Django 2.2.1 on 2019-08-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
